FROM php:8.2-fpm

RUN apt-get update \
    && apt-get install -y --no-install-recommends libjpeg62-turbo-dev libpng-dev libwebp-dev libzip-dev libonig-dev \
    && docker-php-ext-configure gd --with-jpeg --with-webp \
    && docker-php-ext-install -j"$(nproc)" pdo_mysql gd exif mbstring zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/mygallery
